### ISSUE TITLE
transparent support for .bnd include

### ISSUE THREAD

**Issue by rotty3000** [TomDmitriev/gradle-bundle-plugin#7]
I rather like to place the bnd headers in .bnd files.

So currently I'm using:

``` .groovy
bundle {
    instruction '-include', 'bnd.bnd'
}
```

which is nice. 

However, what would be nicer is if either root bnd.bnd or <projectname>.bnd files were loaded automatically if existing.

Need to determine the order of precedence that might have in relation to the build.gradle configurations.

**Comment by paulvi** [comment]
I second the request.

Also think that the best way is to use `bnd.bnd` if present by default.

And for users to keep instructions in external `.bnd` file, rather than in `.gradle`  file

**Comment by TomDmitriev** [comment]
Aren't .bnd files plain Java properties files?
Yes, they are, and one can use `-include` to read any properties files in any order, being the default bndlib setup or any other setup.

**Comment by paulvi** [comment]
Yes, they are. ( so for example in Eclipse IDE right-click, Open with -> Other ... select Properties File Editor check "Use this editor for.." and check "Use this editor for all '*.nbd' files")

This issue is about making line `instruction '-include', 'bnd.bnd'` implied by default when bnd.bnd file is present. That would be in user facing README and incourage users to write instructions in external bnd.bnd file.

However, @rotty3000 Raymond, this is not that much of code. And what is user needs to not use `bnd.bnd` .. then he/she would need to change that file name ...

@rotty3000 Can the issue be closed just by showing example in README

```gradle
bundle {
    instruction '-include', 'bnd.bnd'
}
```
